# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\walroth\Documents\repos\xdart\xdart\gui\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 569)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainSplitter = QtWidgets.QSplitter(self.centralwidget)
        self.mainSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.mainSplitter.setObjectName("mainSplitter")
        self.fileView = QtWidgets.QTreeWidget(self.mainSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileView.sizePolicy().hasHeightForWidth())
        self.fileView.setSizePolicy(sizePolicy)
        self.fileView.setObjectName("fileView")
        self.fileView.headerItem().setText(0, "1")
        self.dataViewer = QtWidgets.QTabWidget(self.mainSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataViewer.sizePolicy().hasHeightForWidth())
        self.dataViewer.setSizePolicy(sizePolicy)
        self.dataViewer.setObjectName("dataViewer")
        self.static = QtWidgets.QWidget()
        self.static.setObjectName("static")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.static)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.staticSplitter = QtWidgets.QSplitter(self.static)
        self.staticSplitter.setOrientation(QtCore.Qt.Vertical)
        self.staticSplitter.setObjectName("staticSplitter")
        self.staticCanvas = QtWidgets.QFrame(self.staticSplitter)
        self.staticCanvas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.staticCanvas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.staticCanvas.setObjectName("staticCanvas")
        self.staticControls = QtWidgets.QFrame(self.staticSplitter)
        self.staticControls.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.staticControls.setFrameShadow(QtWidgets.QFrame.Raised)
        self.staticControls.setObjectName("staticControls")
        self.gridLayout_2.addWidget(self.staticSplitter, 0, 0, 1, 1)
        self.dataViewer.addTab(self.static, "")
        self.dynamic = QtWidgets.QWidget()
        self.dynamic.setObjectName("dynamic")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dynamic)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dynamicSplitter = QtWidgets.QSplitter(self.dynamic)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.dynamicSplitter.sizePolicy().hasHeightForWidth())
        self.dynamicSplitter.setSizePolicy(sizePolicy)
        self.dynamicSplitter.setOrientation(QtCore.Qt.Vertical)
        self.dynamicSplitter.setObjectName("dynamicSplitter")
        self.dynamicCanvas = QtWidgets.QFrame(self.dynamicSplitter)
        self.dynamicCanvas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dynamicCanvas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dynamicCanvas.setObjectName("dynamicCanvas")
        self.dynamicControls = QtWidgets.QFrame(self.dynamicSplitter)
        self.dynamicControls.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dynamicControls.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dynamicControls.setObjectName("dynamicControls")
        self.gridLayout_3.addWidget(self.dynamicSplitter, 0, 0, 1, 1)
        self.commandFrame = QtWidgets.QFrame(self.dynamic)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.commandFrame.sizePolicy().hasHeightForWidth())
        self.commandFrame.setSizePolicy(sizePolicy)
        self.commandFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.commandFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.commandFrame.setObjectName("commandFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.commandFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sendButton = QtWidgets.QPushButton(self.commandFrame)
        self.sendButton.setEnabled(True)
        self.sendButton.setObjectName("sendButton")
        self.gridLayout_4.addWidget(self.sendButton, 0, 2, 1, 1)
        self.commandLine_2 = QtWidgets.QLineEdit(self.commandFrame)
        self.commandLine_2.setObjectName("commandLine_2")
        self.gridLayout_4.addWidget(self.commandLine_2, 0, 1, 1, 1)
        self.responseLine = QtWidgets.QLabel(self.commandFrame)
        self.responseLine.setText("")
        self.responseLine.setObjectName("responseLine")
        self.gridLayout_4.addWidget(self.responseLine, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.commandFrame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.connectButton = QtWidgets.QPushButton(self.commandFrame)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout_4.addWidget(self.connectButton, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.commandFrame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.commandFrame, 1, 0, 1, 1)
        self.dataViewer.addTab(self.dynamic, "")
        self.gridLayout.addWidget(self.mainSplitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 21))
        self.menubar.setDefaultUp(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.dataViewer.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dataViewer.setTabText(self.dataViewer.indexOf(self.static), _translate("MainWindow", "Data"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.label_2.setText(_translate("MainWindow", "Inpt"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.label_3.setText(_translate("MainWindow", "Outpt"))
        self.dataViewer.setTabText(self.dataViewer.indexOf(self.dynamic), _translate("MainWindow", "Live"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))

