# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'displayFrameUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1440, 902)
        self.layout = QtWidgets.QHBoxLayout(Form)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setSpacing(0)
        self.layout.setObjectName("layout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(4, 0, 4, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushLeft = QtWidgets.QPushButton(self.frame)
        self.pushLeft.setObjectName("pushLeft")
        self.verticalLayout_2.addWidget(self.pushLeft)
        self.pushLeftLast = QtWidgets.QPushButton(self.frame)
        self.pushLeftLast.setObjectName("pushLeftLast")
        self.verticalLayout_2.addWidget(self.pushLeftLast)
        self.layout.addWidget(self.frame)
        self.splitter = QtWidgets.QSplitter(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.imageWindow = QtWidgets.QFrame(self.splitter)
        self.imageWindow.setMinimumSize(QtCore.QSize(0, 440))
        self.imageWindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageWindow.setLineWidth(3)
        self.imageWindow.setObjectName("imageWindow")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.imageWindow)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.twoDWindow = QtWidgets.QFrame(self.imageWindow)
        self.twoDWindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.twoDWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.twoDWindow.setObjectName("twoDWindow")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.twoDWindow)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(self.twoDWindow)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(2)
        self.splitter_2.setObjectName("splitter_2")
        self.imageFrame = QtWidgets.QFrame(self.splitter_2)
        self.imageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageFrame.setObjectName("imageFrame")
        self.binnedFrame = QtWidgets.QFrame(self.splitter_2)
        self.binnedFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.binnedFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.binnedFrame.setObjectName("binnedFrame")
        self.horizontalLayout_3.addWidget(self.splitter_2)
        self.verticalLayout_3.addWidget(self.twoDWindow)
        self.imageToolbar = QtWidgets.QFrame(self.imageWindow)
        self.imageToolbar.setMinimumSize(QtCore.QSize(0, 40))
        self.imageToolbar.setMaximumSize(QtCore.QSize(16777215, 45))
        self.imageToolbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageToolbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageToolbar.setObjectName("imageToolbar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.imageToolbar)
        self.horizontalLayout_2.setContentsMargins(12, 6, -1, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imageNormLabel = QtWidgets.QLabel(self.imageToolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageNormLabel.sizePolicy().hasHeightForWidth())
        self.imageNormLabel.setSizePolicy(sizePolicy)
        self.imageNormLabel.setMinimumSize(QtCore.QSize(85, 0))
        self.imageNormLabel.setMaximumSize(QtCore.QSize(90, 16777215))
        self.imageNormLabel.setObjectName("imageNormLabel")
        self.horizontalLayout_2.addWidget(self.imageNormLabel)
        self.imageNorm = QtWidgets.QComboBox(self.imageToolbar)
        self.imageNorm.setMinimumSize(QtCore.QSize(100, 0))
        self.imageNorm.setMaximumSize(QtCore.QSize(200, 16777215))
        self.imageNorm.setObjectName("imageNorm")
        self.imageNorm.addItem("")
        self.imageNorm.addItem("")
        self.imageNorm.addItem("")
        self.horizontalLayout_2.addWidget(self.imageNorm)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.imageUnit = QtWidgets.QComboBox(self.imageToolbar)
        self.imageUnit.setMinimumSize(QtCore.QSize(100, 0))
        self.imageUnit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.imageUnit.setObjectName("imageUnit")
        self.imageUnit.addItem("")
        self.imageUnit.addItem("")
        self.imageUnit.addItem("")
        self.horizontalLayout_2.addWidget(self.imageUnit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.imageMask = QtWidgets.QCheckBox(self.imageToolbar)
        self.imageMask.setObjectName("imageMask")
        self.horizontalLayout_2.addWidget(self.imageMask)
        self.verticalLayout_3.addWidget(self.imageToolbar)
        self.plotWindow = QtWidgets.QFrame(self.splitter)
        self.plotWindow.setMinimumSize(QtCore.QSize(0, 400))
        self.plotWindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotWindow.setLineWidth(3)
        self.plotWindow.setObjectName("plotWindow")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.plotWindow)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.oneDWindow = QtWidgets.QFrame(self.plotWindow)
        self.oneDWindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.oneDWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.oneDWindow.setObjectName("oneDWindow")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.oneDWindow)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter_3 = QtWidgets.QSplitter(self.oneDWindow)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setHandleWidth(2)
        self.splitter_3.setObjectName("splitter_3")
        self.plotFrame = QtWidgets.QFrame(self.splitter_3)
        self.plotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotFrame.setObjectName("plotFrame")
        self.horizontalLayout_4.addWidget(self.splitter_3)
        self.verticalLayout_4.addWidget(self.oneDWindow)
        self.plotToolBar = QtWidgets.QFrame(self.plotWindow)
        self.plotToolBar.setMinimumSize(QtCore.QSize(0, 40))
        self.plotToolBar.setMaximumSize(QtCore.QSize(16777215, 45))
        self.plotToolBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotToolBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotToolBar.setObjectName("plotToolBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.plotToolBar)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scaleLabel = QtWidgets.QLabel(self.plotToolBar)
        self.scaleLabel.setMaximumSize(QtCore.QSize(40, 16777215))
        self.scaleLabel.setObjectName("scaleLabel")
        self.horizontalLayout.addWidget(self.scaleLabel)
        self.plotScale = QtWidgets.QComboBox(self.plotToolBar)
        self.plotScale.setMaximumSize(QtCore.QSize(100, 16777215))
        self.plotScale.setObjectName("plotScale")
        self.plotScale.addItem("")
        self.plotScale.addItem("")
        self.plotScale.addItem("")
        self.horizontalLayout.addWidget(self.plotScale)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.plotMethod = QtWidgets.QComboBox(self.plotToolBar)
        self.plotMethod.setObjectName("plotMethod")
        self.plotMethod.addItem("")
        self.plotMethod.addItem("")
        self.plotMethod.addItem("")
        self.horizontalLayout.addWidget(self.plotMethod)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.yOffsetLabel = QtWidgets.QLabel(self.plotToolBar)
        self.yOffsetLabel.setMaximumSize(QtCore.QSize(55, 16777215))
        self.yOffsetLabel.setObjectName("yOffsetLabel")
        self.horizontalLayout.addWidget(self.yOffsetLabel)
        self.yOffsetSlider = QtWidgets.QSlider(self.plotToolBar)
        self.yOffsetSlider.setMaximumSize(QtCore.QSize(250, 16777215))
        self.yOffsetSlider.setMaximum(100)
        self.yOffsetSlider.setProperty("value", 5)
        self.yOffsetSlider.setOrientation(QtCore.Qt.Horizontal)
        self.yOffsetSlider.setObjectName("yOffsetSlider")
        self.horizontalLayout.addWidget(self.yOffsetSlider)
        spacerItem4 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.plotUnit = QtWidgets.QComboBox(self.plotToolBar)
        self.plotUnit.setMinimumSize(QtCore.QSize(70, 0))
        self.plotUnit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.plotUnit.setObjectName("plotUnit")
        self.plotUnit.addItem("")
        self.plotUnit.addItem("")
        self.horizontalLayout.addWidget(self.plotUnit)
        spacerItem5 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.plotOverlay = QtWidgets.QCheckBox(self.plotToolBar)
        self.plotOverlay.setObjectName("plotOverlay")
        self.horizontalLayout.addWidget(self.plotOverlay)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_4.addWidget(self.plotToolBar)
        self.layout.addWidget(self.splitter)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(4, 0, 4, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushRight = QtWidgets.QPushButton(self.frame_2)
        self.pushRight.setObjectName("pushRight")
        self.verticalLayout.addWidget(self.pushRight)
        self.pushRightLast = QtWidgets.QPushButton(self.frame_2)
        self.pushRightLast.setObjectName("pushRightLast")
        self.verticalLayout.addWidget(self.pushRightLast)
        self.layout.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushLeft.setText(_translate("Form", "<"))
        self.pushLeftLast.setText(_translate("Form", "<<"))
        self.imageNormLabel.setText(_translate("Form", "Normalize to"))
        self.imageNorm.setItemText(0, _translate("Form", "None"))
        self.imageNorm.setItemText(1, _translate("Form", "Monitor"))
        self.imageNorm.setItemText(2, _translate("Form", "Time"))
        self.imageUnit.setItemText(0, _translate("Form", "Q Chi"))
        self.imageUnit.setItemText(1, _translate("Form", "Qz Qxy"))
        self.imageUnit.setItemText(2, _translate("Form", "2 u\\u03B8 Chi"))
        self.imageMask.setText(_translate("Form", "Mask"))
        self.scaleLabel.setText(_translate("Form", "Scale"))
        self.plotScale.setItemText(0, _translate("Form", "Linear"))
        self.plotScale.setItemText(1, _translate("Form", "Log"))
        self.plotScale.setItemText(2, _translate("Form", "Sqrt"))
        self.plotMethod.setItemText(0, _translate("Form", "Overlay"))
        self.plotMethod.setItemText(1, _translate("Form", "Average"))
        self.plotMethod.setItemText(2, _translate("Form", "Waterfall"))
        self.yOffsetLabel.setText(_translate("Form", "y Offset"))
        self.plotUnit.setItemText(0, _translate("Form", "2 u\\u03B8"))
        self.plotUnit.setItemText(1, _translate("Form", "q (A-1)"))
        self.plotOverlay.setText(_translate("Form", "Overlay"))
        self.pushRight.setText(_translate("Form", ">"))
        self.pushRightLast.setText(_translate("Form", ">>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
