# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'specUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1440, 369)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.paramFrame = QtWidgets.QFrame(Form)
        self.paramFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.paramFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.paramFrame.setObjectName("paramFrame")
        self.verticalLayout.addWidget(self.paramFrame)
        self.specLabel = QtWidgets.QLabel(Form)
        self.specLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.specLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.specLabel.setText("")
        self.specLabel.setObjectName("specLabel")
        self.verticalLayout.addWidget(self.specLabel)
        self.commandFrame = QtWidgets.QFrame(Form)
        self.commandFrame.setMinimumSize(QtCore.QSize(0, 40))
        self.commandFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.commandFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.commandFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.commandFrame.setObjectName("commandFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.commandFrame)
        self.horizontalLayout_2.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.commandLayout = QtWidgets.QHBoxLayout()
        self.commandLayout.setObjectName("commandLayout")
        self.horizontalLayout_2.addLayout(self.commandLayout)
        self.verticalLayout.addWidget(self.commandFrame)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.frame)
        self.startButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.pauseButton = QtWidgets.QPushButton(self.frame)
        self.pauseButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout.addWidget(self.pauseButton)
        self.continueButton = QtWidgets.QPushButton(self.frame)
        self.continueButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.continueButton.setObjectName("continueButton")
        self.horizontalLayout.addWidget(self.continueButton)
        self.stopButton = QtWidgets.QPushButton(self.frame)
        self.stopButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.startButton.setText(_translate("Form", "Start"))
        self.pauseButton.setText(_translate("Form", "Pause"))
        self.continueButton.setText(_translate("Form", "Continue"))
        self.stopButton.setText(_translate("Form", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
